// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Position } from "./Position";

/**
 * Result of `anchor/resolve`.
 */
export type AnchorResolveResult = { position: Position, valid: boolean, };
