// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WireAnchorToken } from "./WireAnchorToken";

/**
 * Result of `anchor/create`.
 */
export type AnchorCreateResult = { anchor: WireAnchorToken, };
