// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Position } from "./Position";
import type { WireBias } from "./WireBias";

/**
 * Params for `anchor/create`.
 */
export type AnchorCreateParams = { bufferId: number, position: Position,
/**
 * Defaults to `Right` (stick after inserted text) when absent.
 */
bias?: WireBias | null, };
