// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WireVersion } from "./WireVersion";

/**
 * Result of `buffer/text`.
 */
export type BufferTextResult = { text: string, version: WireVersion, };
