// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params for `buffer/unsubscribe`.
 */
export type BufferUnsubscribeParams = { bufferId: number, };
