// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SavedMtime } from "./SavedMtime";
import type { WireVersion } from "./WireVersion";

/**
 * Result of `buffer/save`.
 */
export type BufferSaveResult = { version: WireVersion, savedMtime: SavedMtime | null, };
