// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WireVersion } from "./WireVersion";

/**
 * One entry returned by `buffer/list`.
 */
export type BufferInfo = { bufferId: number, path: string | null, worktreeId: number | null, dirty: boolean, version: WireVersion, };
