// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params for `buffer/open`.
 */
export type BufferOpenParams = {
/**
 * A concrete `workspaceId` OR the literal sentinel `"current-active"`.
 */
workspace: string,
/**
 * Absolute filesystem path, or a path relative to one of the workspace's
 * visible worktree roots.
 */
path: string, };
