// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params for `buffer/subscribe`.
 */
export type BufferSubscribeParams = { bufferId: number, };
