// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WireVersion } from "./WireVersion";

/**
 * Result of `buffer/subscribe`.
 *
 * Establishes the **baseline** the subscriber is expected to hold: `text` is
 * the buffer contents at `version`, captured atomically with the subscription
 * registration. The client stores `text` as its current document and the
 * server initialises that subscriber's delivery cursor to `version`; every
 * subsequent `buffer/didChange` diffs forward from there (ranges in the
 * client's held frame). No edit can interleave between this snapshot and the
 * first delivered notification.
 */
export type BufferSubscribeResult = { bufferId: number, version: WireVersion, text: string, };
