// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WireVersion } from "./WireVersion";

/**
 * Result of `buffer/open`.
 */
export type BufferOpenResult = { bufferId: number, path: string | null, version: WireVersion, };
