// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WireVersion } from "./WireVersion";

/**
 * Result of `buffer/edit`.
 */
export type BufferEditResult = { version: WireVersion, lamport: number | null, };
