// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Range } from "./Range";

/**
 * One edit inside `buffer/edit`.
 */
export type BufferEdit = { range: Range, newText: string, };
