// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Range } from "./Range";

/**
 * Params for `buffer/text`.
 */
export type BufferTextParams = { bufferId: number, range?: Range | null, };
