// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BufferEdit } from "./BufferEdit";
import type { WireVersion } from "./WireVersion";

/**
 * Params for `buffer/edit`.
 */
export type BufferEditParams = { bufferId: number, edits: Array<BufferEdit>, baseVersion?: WireVersion | null, autoindent?: boolean | null, source?: string | null, };
