// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WireVersion } from "./WireVersion";

/**
 * Typed JSON-RPC error data for `buffer/edit` base-version conflicts.
 */
export type ConflictErrorData = { kind: string, currentVersion: WireVersion, };
