// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WireChange } from "./WireChange";
import type { WireVersion } from "./WireVersion";

/**
 * `buffer/didChange` notification params (constraint 4 — pre-edit frame).
 */
export type DidChangeParams = { bufferId: number, version: WireVersion,
/**
 * Changes in the subscriber's held (pre-edit) frame, ordered descending by
 * start so naive in-order application reconstructs the new text exactly.
 */
changes: Array<WireChange>, isLocal: boolean, };
