// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `buffer/didOpen` notification params.
 */
export type DidOpenParams = { bufferId: number, path?: string | null, };
