// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SavedMtime } from "./SavedMtime";
import type { WireVersion } from "./WireVersion";

/**
 * `buffer/didSave` notification params.
 */
export type DidSaveParams = { bufferId: number, version: WireVersion, savedMtime?: SavedMtime | null, };
