// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A server→client JSON-RPC 2.0 notification (no `id`).
 *
 * Emitted on a subscribed connection's bounded outbound channel for
 * `buffer/didChange`, `buffer/didSave`, `buffer/didOpen`, `buffer/didClose`.
 */
export type Notification = { jsonrpc: string, method: string, params: JsonValue, };
