// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire-format position: UTF-16 `{line, character}` with an optional `{offset}`
 * byte form.
 *
 * Both `line` and `character` are **0-indexed**.  When `offset` is present the
 * server uses it directly and ignores `{line, character}`.
 */
export type Position = {
/**
 * 0-indexed line number.
 */
line: number,
/**
 * 0-indexed UTF-16 code-unit column within the line.
 */
character: number,
/**
 * Optional byte offset in the document text.  When present, takes
 * precedence over `{line, character}`.
 */
offset?: number | null, };
