// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Position } from "./Position";

/**
 * Wire-format range expressed as two [`Position`]s (both 0-indexed, inclusive
 * start / exclusive end following LSP convention).
 */
export type Range = { start: Position, end: Position, };
