// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type Request = { jsonrpc: string, id?: JsonValue | null, method: string, params?: JsonValue | null, };
