// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResponseError } from "./ResponseError";
import type { JsonValue } from "./serde_json/JsonValue";

export type Response = { jsonrpc: string, id: JsonValue | null, result?: JsonValue | null, error?: ResponseError | null, };
