// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Opaque wire token representing a [`text::Anchor`].
 *
 * The client treats this as a black box; the server encodes/decodes it via
 * [`encode_anchor`] / [`decode_anchor`].  The token is a base64url-encoded
 * fixed-width byte array derived from `Anchor::opaque_id()` (20 bytes).
 */
export type WireAnchorToken = string;
