// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire form of a [`clock::Global`] version vector.
 *
 * A dense `Vec<u32>` where index `i` holds the highest sequence number
 * observed for replica `i`.  Trailing zeroes are stripped on encode and
 * implied as zero on decode.
 */
export type WireVersion = Array<number>;
