// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Range } from "./Range";

/**
 * One element of the `changes` array in a `buffer/didChange` notification.
 *
 * `range` is in the **pre-edit/base coordinate frame** (UTF-16 `{line,
 * character}`); `new_text` is the replacement text (empty = pure deletion).
 *
 * Applying the changes **in order** against the client's previous text
 * exactly reproduces the new server text (spec §2, constraint 4).
 */
export type WireChange = {
/**
 * Range in the pre-edit text expressed as UTF-16 `{line, character}` positions.
 */
range: Range,
/**
 * Replacement text (empty string = pure deletion).
 */
newText: string, };
