// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Anchor bias on the wire (`Left` ≈ `anchor_before`, `Right` ≈ `anchor_after`).
 */
export type WireBias = "left" | "right";
