// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params carrying only a required `workspace` target.
 */
export type WorkspaceTargetParams = {
/**
 * A concrete `workspaceId` OR the literal sentinel `"current-active"`.
 */
workspace: string, };
