// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry returned by `workspace/list`.
 */
export type WorkspaceInfo = {
/**
 * Opaque, ephemeral handle (the active `Workspace`'s runtime `EntityId`,
 * stringified). Does not survive window/workspace churn — see constraint 7.
 */
workspaceId: string,
/**
 * Absolute paths of the workspace's visible worktree roots.
 */
rootPaths: Array<string>,
/**
 * True for the currently-focused window.
 */
active: boolean, };
